System-wide installation improvements
ThomasTJdev/nim_homeassistant pull request #34
Opened 2019-03-30 18:21 UTC by FedericoCeratto

Add contributing guide
Add Debian packaging, initial version
Prepare NimHA for system-wide installation
Handle system-wide paths
Setup Nimble in dedicated dir and install build deps
Code cleanup

2019-04-17 07:39 UTC, ThomasTJdev requested changes
Sorry for the slow review.

All of the `-d:release` marked #installpath needs to manually created. How do you plan to do this? A manually check/copy at init when running in `release`?
The master branch needs to be automated. I can create a devel-branch we can work on, where the automation process for the lazy user can be implemented at the end?

2019-04-17 07:39 UTC, ThomasTJdev commented on nimha.nim
> +    discard existsOrCreateDir(getTmpDir())
`getTmpDir()` requires a param:
```
proc getTmpDir*(modulename: string): string =
```
==>
```
proc getTmpDir*(modulename = ""): string =
```

2019-04-17 07:42 UTC, ThomasTJdev commented
> Sorry for the slow review.
> 
> All of the `-d:release` marked #installpath needs to manually created. How do you plan to do this? A manually check/copy at init when running in `release`?
> The master branch needs to be automated. I can create a devel-branch we can work on, where the automation process for the lazy user can be implemented at the end?

Ohh give me a sec. I didn't checkout the debian files.

2019-04-17 12:51 UTC, FedericoCeratto commented
Creating system users, groups, directories, config files is left to the installer. apt, zypper, and a (yet to be written) install.sh do that each in its own way.

2019-04-19 14:48 UTC, ThomasTJdev commented
I'm running Arch which made it a little difficult to test the `-d:release` mode. I tried to combine some bash for a install script - [gist link](https://gist.github.com/ThomasTJdev/898e9de422d5a1c4f33f9b546b46e6b0).

I was able to commit directly to you `devel` branch, but only by pushing to your repo.

I'll merge now, but I'll merge to a devel branch. We'll merge the devel with master, when `-d:release` works for main linux distros - ok?

2019-04-19 14:49 UTC, ThomasTJdev approved these changes

2019-04-19 14:50 UTC, merged